
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = 'A4B2A4662EAB3890B0B607735F0AB018'
    
_lr_action_items = {'STRING':([2,7,8,15,],[5,9,10,10,]),'NUMBER':([8,15,],[11,11,]),'CCORCH':([4,6,10,11,12,13,14,16,],[6,-2,-7,-6,-8,-4,-5,-3,]),'DSPTS':([5,9,],[8,15,]),'VAR':([8,15,],[14,14,]),'ACORCH':([0,8,15,],[2,2,2,]),'COMA':([4,6,10,11,12,13,14,16,],[7,-2,-7,-6,-8,-4,-5,-3,]),'$end':([1,3,6,],[-1,0,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'init':([0,8,15,],[1,12,12,]),'valor':([8,15,],[13,16,]),'cnt':([2,],[4,]),'inicio':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> inicio","S'",1,None,None,None),
  ('inicio -> init','inicio',1,'p_iniciando','parser_rules.py',10),
  ('init -> ACORCH cnt CCORCH','init',3,'p_contenido','parser_rules.py',14),
  ('cnt -> cnt COMA STRING DSPTS valor','cnt',5,'p_lista','parser_rules.py',18),
  ('cnt -> STRING DSPTS valor','cnt',3,'p_lista','parser_rules.py',19),
  ('valor -> VAR','valor',1,'p_valorVar','parser_rules.py',46),
  ('valor -> NUMBER','valor',1,'p_valorNumber','parser_rules.py',53),
  ('valor -> STRING','valor',1,'p_valorString','parser_rules.py',60),
  ('valor -> init','valor',1,'p_valorInit','parser_rules.py',67),
]
